rootProject.name = 'modern-java'
include 'checkout-service'
include 'explore-latest-java-features'
include '../modules/modern-java/moduleone'
findProject(':../modules/modern-java/moduleone')?.name = 'moduleone'
include 'modules:moduleone'
findProject(':modules:moduleone')?.name = 'moduleone'
include 'modules:moduletwo'
findProject(':modules:moduletwo')?.name = 'moduletwo'
include 'modules:modulethree'
findProject(':modules:modulethree')?.name = 'modulethree'
include 'modules:modulefour'
findProject(':modules:modulefour')?.name = 'modulefour'

